"""Rich HTML email renderers for MemoryOS skill reports.

Builds executive-quality HTML emails from structured JSON data with:
  - Inline CSS only (no <style> blocks -- Outlook strips them)
  - Base64-embedded images (survive forwarding)
  - PIL resize to keep email size under 2 MB
"""

from __future__ import annotations

import base64
import io
import logging
import re
from pathlib import Path
from typing import Any

logger = logging.getLogger("memoryos.agents.email_renderer")

_MAX_IMG_WIDTH = 800

# ── Colour palette ────────────────────────────────────────────────────────────

_C = {
    "bg": "#0f1117",
    "card": "#1a1d28",
    "card_border": "#2a2d3a",
    "accent": "#6c7cff",
    "accent_light": "#8b97ff",
    "text": "#e2e4ea",
    "muted": "#8b8fa3",
    "white": "#ffffff",
    "green": "#4ade80",
    "yellow": "#facc15",
    "red": "#f87171",
    "blue": "#60a5fa",
    "orange": "#fb923c",
    "body_bg": "#f8f9fa",
    "body_text": "#1a1a2e",
    "body_muted": "#6b7280",
    "body_card": "#ffffff",
    "body_border": "#e5e7eb",
    "header_gradient_start": "#1a1d28",
    "header_gradient_end": "#0f1117",
}


# ── Image helpers ─────────────────────────────────────────────────────────────

def _resize_image_bytes(raw: bytes, max_width: int = _MAX_IMG_WIDTH) -> bytes:
    """Resize a PNG to *max_width*, returning JPEG bytes for smaller payloads."""
    try:
        from PIL import Image
        img = Image.open(io.BytesIO(raw))
        if img.width > max_width:
            ratio = max_width / img.width
            img = img.resize(
                (max_width, int(img.height * ratio)),
                Image.LANCZOS,
            )
        if img.mode in ("RGBA", "P"):
            img = img.convert("RGB")
        buf = io.BytesIO()
        img.save(buf, format="JPEG", quality=82, optimize=True)
        return buf.getvalue()
    except Exception:
        return raw


def _embed_image(path: Path | str) -> str | None:
    """Return a ``data:image/...;base64,...`` URI, or None on failure."""
    p = Path(path)
    if not p.is_file():
        return None
    try:
        raw = p.read_bytes()
        resized = _resize_image_bytes(raw)
        b64 = base64.b64encode(resized).decode("ascii")
        mime = "image/jpeg"
        return f"data:{mime};base64,{b64}"
    except Exception as exc:
        logger.warning("Failed to embed image %s: %s", path, exc)
        return None


def _find_hero_image(images_dir: Path) -> str | None:
    """Find and embed the first hero/infographic image in the directory."""
    if not images_dir.is_dir():
        return None
    for f in sorted(images_dir.iterdir()):
        if f.suffix.lower() in (".png", ".jpg", ".jpeg"):
            return _embed_image(f)
    return None


# ── HTML building blocks ──────────────────────────────────────────────────────

def _email_wrapper(title: str, date: str, subtitle: str, body_html: str, hero_uri: str | None = None) -> str:
    hero = ""
    if hero_uri:
        hero = (
            f'<img src="{hero_uri}" alt="" '
            f'style="display:block;width:100%;max-height:300px;object-fit:cover;'
            f'object-position:center 30%;border-radius:0 0 12px 12px;" />'
        )
    return f"""<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width"></head>
<body style="margin:0;padding:0;background:{_C['body_bg']};font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:{_C['body_bg']};">
<tr><td align="center" style="padding:0;">
<table width="680" cellpadding="0" cellspacing="0" style="max-width:680px;width:100%;background:{_C['body_card']};border-radius:12px;overflow:hidden;margin:20px auto;box-shadow:0 2px 12px rgba(0,0,0,0.08);">

<!-- Header -->
<tr><td style="background:linear-gradient(135deg,{_C['header_gradient_start']},{_C['header_gradient_end']});padding:32px 36px 24px;">
  <div style="font-size:11px;text-transform:uppercase;letter-spacing:2px;color:{_C['accent_light']};margin-bottom:8px;">MemoryOS</div>
  <div style="font-size:24px;font-weight:700;color:{_C['white']};line-height:1.3;">{title}</div>
  <div style="font-size:14px;color:{_C['muted']};margin-top:6px;">{date} &middot; {subtitle}</div>
</td></tr>

{f'<tr><td style="padding:0;">{hero}</td></tr>' if hero else ''}

<!-- Body -->
<tr><td style="padding:28px 36px 36px;color:{_C['body_text']};font-size:15px;line-height:1.65;">
{body_html}
</td></tr>

<!-- Footer -->
<tr><td style="padding:20px 36px;border-top:1px solid {_C['body_border']};font-size:12px;color:{_C['body_muted']};text-align:center;">
  Generated by MemoryOS &middot; Your AI-powered executive intelligence system
</td></tr>

</table>
</td></tr>
</table>
</body></html>"""


def _section(title: str, content: str) -> str:
    return (
        f'<div style="margin-top:28px;">'
        f'<div style="font-size:13px;text-transform:uppercase;letter-spacing:1.5px;'
        f'color:{_C["accent"]};font-weight:700;margin-bottom:14px;'
        f'border-bottom:2px solid {_C["accent"]};padding-bottom:6px;">{title}</div>'
        f'{content}</div>'
    )


def _card(title: str, body: str = "", meta: str = "", accent_left: str = "") -> str:
    border = f"border-left:4px solid {accent_left};" if accent_left else ""
    return (
        f'<div style="background:{_C["body_card"]};border:1px solid {_C["body_border"]};'
        f'border-radius:8px;padding:16px 18px;margin-bottom:10px;{border}">'
        f'<div style="font-weight:600;font-size:14px;color:{_C["body_text"]};">{title}</div>'
        + (f'<div style="font-size:13px;color:{_C["body_text"]};margin-top:6px;line-height:1.5;">{body}</div>' if body else '')
        + (f'<div style="font-size:12px;color:{_C["body_muted"]};margin-top:6px;">{meta}</div>' if meta else '')
        + '</div>'
    )


def _pill(label: str, color: str) -> str:
    return (
        f'<span style="display:inline-block;padding:2px 10px;border-radius:12px;'
        f'font-size:11px;font-weight:600;color:#fff;background:{color};'
        f'text-transform:uppercase;letter-spacing:0.5px;">{label}</span>'
    )


def _metric_box(value: str, label: str) -> str:
    return (
        f'<td style="text-align:center;padding:12px 8px;">'
        f'<div style="font-size:28px;font-weight:800;color:{_C["accent"]};">{value}</div>'
        f'<div style="font-size:11px;color:{_C["body_muted"]};text-transform:uppercase;'
        f'letter-spacing:0.5px;margin-top:2px;">{label}</div></td>'
    )


def _metrics_bar(metrics: list[tuple[str, str]]) -> str:
    cols = "".join(_metric_box(v, l) for v, l in metrics)
    return (
        f'<table width="100%" cellpadding="0" cellspacing="0" '
        f'style="background:{_C["body_card"]};border:1px solid {_C["body_border"]};'
        f'border-radius:10px;margin-bottom:24px;"><tr>{cols}</tr></table>'
    )


def _severity_color(s: str) -> str:
    return {"critical": _C["red"], "high": _C["orange"], "warning": _C["yellow"],
            "medium": _C["yellow"], "low": _C["blue"], "info": _C["blue"]}.get(s, _C["muted"])


def _urgency_pill(u: str) -> str:
    colors = {"critical": _C["red"], "high": _C["orange"], "medium": _C["yellow"], "low": _C["blue"]}
    return _pill(u, colors.get(u, _C["muted"]))


def _status_pill(s: str) -> str:
    colors = {"On Track": _C["green"], "In Progress": _C["blue"], "Delivered": _C["green"],
              "At Risk": _C["yellow"], "Overdue": _C["red"], "Missed": _C["red"],
              "Due": _C["yellow"], "Deferred": _C["muted"], "Not Started": _C["muted"]}
    return _pill(s, colors.get(s, _C["muted"]))


_EDITORIAL_JUNK = re.compile(
    r"^(Hero image:|alt:|https?://)\S*.*$", re.MULTILINE | re.IGNORECASE,
)


def _clean_editorial(text: str) -> str:
    """Strip LLM-injected hero image metadata from editorial_frame text."""
    return _EDITORIAL_JUNK.sub("", text).strip()


def _esc(s: str | None) -> str:
    if not s:
        return ""
    return str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def _progress_bar(percent: int, color: str | None = None) -> str:
    """CSS-only progress bar for emails (no JavaScript needed)."""
    if color is None:
        color = _C["green"] if percent >= 75 else _C["yellow"] if percent >= 50 else _C["red"]
    return (
        f'<div style="background:{_C["body_border"]};border-radius:4px;height:8px;'
        f'margin-top:6px;overflow:hidden;">'
        f'<div style="background:{color};width:{min(100, percent)}%;height:100%;'
        f'border-radius:4px;"></div></div>'
    )


def _score_badge(score: int, label: str) -> str:
    """Circular score badge rendered as an HTML table cell."""
    color = _C["green"] if score >= 75 else _C["yellow"] if score >= 50 else _C["red"]
    return (
        f'<td style="text-align:center;padding:12px 16px;vertical-align:top;">'
        f'<div style="width:80px;height:80px;border-radius:50%;'
        f'border:4px solid {color};display:inline-flex;align-items:center;'
        f'justify-content:center;margin-bottom:4px;">'
        f'<span style="font-size:28px;font-weight:800;color:{color};">{score}</span></div>'
        f'<div style="font-size:11px;color:{_C["body_muted"]};text-transform:uppercase;'
        f'letter-spacing:0.5px;">{label}</div></td>'
    )


def _delta_arrow(value: float, unit: str = "", inverse: bool = False) -> str:
    """Render a delta value with colored arrow. inverse=True means lower is better."""
    positive = value >= 0
    good = (not positive) if inverse else positive
    color = _C["green"] if good else _C["red"]
    arrow = "&#9650;" if positive else "&#9660;"
    sign = "+" if positive else ""
    return (
        f'<span style="color:{color};font-weight:700;">'
        f'{arrow} {sign}{value:.1f}{unit}</span>'
    )


def _analysis_card(analysis: dict[str, Any] | None) -> str:
    """Render the LLM analysis block as an email card."""
    if not analysis:
        return ""
    parts = []
    if analysis.get("executive_insight"):
        parts.append(
            f'<div style="font-size:15px;font-weight:600;color:{_C["body_text"]};'
            f'line-height:1.5;margin-bottom:12px;">{_esc(analysis["executive_insight"])}</div>'
        )
    items = []
    if analysis.get("biggest_risk"):
        items.append(f'<b style="color:{_C["red"]};">Risk:</b> {_esc(analysis["biggest_risk"])}')
    if analysis.get("recommended_focus"):
        items.append(f'<b style="color:{_C["green"]};">Focus:</b> {_esc(analysis["recommended_focus"])}')
    if items:
        parts.append('<div style="font-size:13px;line-height:1.6;">' + '<br>'.join(items) + '</div>')
    if analysis.get("predictions"):
        preds = "".join(f"<li>{_esc(p)}</li>" for p in analysis["predictions"])
        parts.append(
            f'<div style="margin-top:8px;font-size:12px;color:{_C["body_muted"]};">'
            f'<b>Predictions:</b><ul style="margin:4px 0 0 16px;">{preds}</ul></div>'
        )
    content = "".join(parts)
    return (
        f'<div style="background:rgba(108,124,255,0.04);border:1px solid rgba(108,124,255,0.15);'
        f'border-radius:10px;padding:18px 20px;margin-bottom:24px;">{content}</div>'
    )


# ── Morning Brief ─────────────────────────────────────────────────────────────

def render_morning_brief_email(json_data: dict[str, Any], images_dir: Path) -> str:
    d = json_data
    hero = _find_hero_image(images_dir)

    score_html = ""
    if d.get("day_score") is not None:
        score_html = (
            f'<table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:16px;"><tr>'
            + _score_badge(d.get("day_score", 0), "Day Score")
            + f'<td style="padding:12px 16px;vertical-align:middle;">'
            + (f'<div style="font-size:16px;font-weight:600;color:{_C["body_text"]};margin-bottom:8px;">{_esc(d.get("day_summary", ""))}</div>' if d.get("day_summary") else '')
            + '</td></tr></table>'
        )

    metrics = _metrics_bar([
        (str(d.get("meeting_count", 0)), "Meetings"),
        (str(d.get("priority_email_count", 0)), "Priority Emails"),
        (str(d.get("unread_reply_count", 0)), "Needs Reply"),
        (str(d.get("commitment_count", 0)), "Commitments"),
    ])

    signals_html = ""
    for s in d.get("signals", []):
        icon = {"deadline": "&#9200;", "escalation": "&#9888;", "risk": "&#9888;", "opportunity": "&#10024;"}.get(s.get("type", ""), "&#8226;")
        signals_html += _card(
            f'{icon} {_esc(s.get("message", ""))}',
            accent_left=_severity_color(s.get("severity", "warning")),
        )

    focus_html = ""
    for p in d.get("priority_focus_areas", []):
        focus_html += _card(
            f'{_urgency_pill(p.get("urgency", ""))} &nbsp; {_esc(p.get("name", ""))}',
            body=_esc(p.get("detail", "")),
        )

    cal_html = ""
    for mtg in d.get("meetings", []):
        priority_color = {"high": _C["red"], "medium": _C["yellow"], "low": _C["green"]}.get(mtg.get("priority", ""), _C["muted"])
        attendees = ", ".join(a.get("name", "") for a in mtg.get("attendees", [])[:5])
        cal_html += _card(
            f'<span style="color:{priority_color};">&#9679;</span> {_esc(mtg.get("time", ""))} &mdash; {_esc(mtg.get("title", ""))}',
            body=_esc(mtg.get("context", "")),
            meta=f"Attendees: {_esc(attendees)}" if attendees else "",
        )

    emails_html = ""
    for e in d.get("priority_emails", []):
        emails_html += _card(
            f'{_urgency_pill(e.get("urgency", ""))} &nbsp; {_esc(e.get("subject", ""))}',
            body=f"<b>Action:</b> {_esc(e.get('action_needed', ''))}" if e.get("action_needed") else "",
            meta=f"From: {_esc(e.get('from', ''))} &middot; {_esc(e.get('time_ago', ''))}",
        )

    commits_html = ""
    for c in d.get("commitments_yours", []):
        commits_html += _card(_esc(c.get("commitment", "")), meta=_esc(c.get("source", "")), accent_left=_C["orange"])
    for c in d.get("commitments_others", []):
        commits_html += _card(f'{_esc(c.get("person", ""))}: {_esc(c.get("commitment", ""))}', meta=_esc(c.get("source", "")))

    body = score_html + metrics + _analysis_card(d.get("analysis"))
    qw = d.get("quick_wins", [])
    if qw:
        qw_html = ""
        for q in qw:
            qw_html += _card(_esc(q.get("action", "")), body=_esc(q.get("impact", "")), meta=_esc(q.get("time_needed", "")), accent_left=_C["green"])
        body += _section("Quick Wins", qw_html)
    if signals_html:
        body += _section("Signals", signals_html)
    if focus_html:
        body += _section("Priority Focus Areas", focus_html)
    if cal_html:
        body += _section(f'Today\'s Calendar ({len(d.get("meetings", []))} meetings)', cal_html)
    if emails_html:
        body += _section(f'Priority Emails ({len(d.get("priority_emails", []))})', emails_html)
    if commits_html:
        body += _section("Commitments", commits_html)

    needs_reply = d.get("needs_reply", [])
    if needs_reply:
        nr_html = ""
        for n in needs_reply:
            nr_html += _card(_esc(n.get("subject", "")), meta=f"From: {_esc(n.get('from', ''))} &middot; {_esc(n.get('time_ago', ''))}", accent_left=_C["yellow"])
        body += _section(f"Needs Your Reply ({len(needs_reply)})", nr_html)

    return _email_wrapper(
        "Morning Intelligence Brief",
        d.get("date", ""),
        f'{d.get("day_of_week", "")} &middot; {d.get("meeting_count", 0)} meetings, {d.get("priority_email_count", 0)} priority emails',
        body,
        hero_uri=hero,
    )


# ── News Pulse ────────────────────────────────────────────────────────────────

def render_news_pulse_email(json_data: dict[str, Any], images_dir: Path) -> str:
    d = json_data
    hero = _find_hero_image(images_dir)

    body = ""

    internal = d.get("internal_signals", [])
    if internal:
        source_icons = {"email": "&#9993;", "meeting": "&#128197;", "teams": "&#128172;", "activity": "&#128187;"}
        int_html = ""
        for sig in internal:
            icon = source_icons.get(sig.get("source_type", ""), "&#8226;")
            urgency = sig.get("urgency", "medium")
            so_what = ""
            if sig.get("so_what"):
                so_what = (
                    f'<div style="background:#f0fff4;border-radius:6px;padding:10px 14px;'
                    f'margin-top:8px;font-size:13px;color:{_C["body_text"]};line-height:1.5;">'
                    f'<b style="color:{_C["green"]};">Implication:</b> {_esc(sig["so_what"])}</div>'
                )
            int_html += (
                f'<div style="background:{_C["body_card"]};border:1px solid {_C["body_border"]};'
                f'border-left:4px solid {_C["green"]};border-radius:8px;padding:16px 18px;margin:10px 0;">'
                f'<div style="display:flex;align-items:center;gap:8px;margin-bottom:6px;">'
                f'{_urgency_pill(urgency)}'
                f'<span style="font-size:12px;color:{_C["body_muted"]};">{icon} {_esc(sig.get("source_detail", ""))}</span>'
                f'</div>'
                f'<div style="font-weight:600;font-size:14px;color:{_C["body_text"]};">'
                f'{_esc(sig.get("title", ""))}</div>'
                f'<div style="font-size:13px;color:{_C["body_text"]};margin-top:6px;line-height:1.5;">'
                f'{_esc(sig.get("summary", ""))}</div>'
                f'{so_what}</div>'
            )
        body += _section("Internal Signals", int_html)

    for topic in d.get("topics", []):
        topic_header = (
            f'<div style="margin-top:28px;margin-bottom:4px;">'
            f'<div style="font-size:13px;text-transform:uppercase;letter-spacing:1.5px;'
            f'color:{_C["accent"]};font-weight:700;padding-bottom:6px;'
            f'border-bottom:2px solid {_C["accent"]};">{_esc(topic.get("name", ""))}</div>'
            f'<div style="font-size:14px;color:{_C["body_muted"]};margin-top:8px;'
            f'font-style:italic;line-height:1.5;">{_esc(_clean_editorial(topic.get("editorial_frame", "")))}</div></div>'
        )
        body += topic_header

        for article in topic.get("articles", []):
            source_link = ""
            if article.get("url"):
                source_link = (
                    f' <a href="{_esc(article["url"])}" style="color:{_C["accent"]};'
                    f'text-decoration:none;font-size:12px;">Read &rarr;</a>'
                )
            so_what = ""
            if article.get("so_what"):
                so_what = (
                    f'<div style="background:#f0f4ff;border-radius:6px;padding:10px 14px;'
                    f'margin-top:8px;font-size:13px;color:{_C["body_text"]};line-height:1.5;">'
                    f'<b style="color:{_C["accent"]};">Why this matters:</b> {_esc(article["so_what"])}</div>'
                )
            body += (
                f'<div style="background:{_C["body_card"]};border:1px solid {_C["body_border"]};'
                f'border-radius:8px;padding:16px 18px;margin:10px 0;">'
                f'<div style="font-weight:600;font-size:14px;color:{_C["body_text"]};">'
                f'{_esc(article.get("title", ""))}{source_link}</div>'
                f'<div style="font-size:13px;color:{_C["body_text"]};margin-top:6px;line-height:1.5;">'
                f'{_esc(article.get("summary", ""))}</div>'
                f'{so_what}'
                f'<div style="font-size:11px;color:{_C["body_muted"]};margin-top:8px;">'
                f'{_esc(article.get("source", ""))} &middot; {_esc(article.get("date", ""))}</div>'
                f'</div>'
            )

    vault_topics = d.get("vault_topics", [])
    if vault_topics:
        vt_html = ""
        for vt in vault_topics:
            for a in vt.get("articles", []):
                link = f' <a href="{_esc(a["url"])}" style="color:{_C["accent"]};text-decoration:none;font-size:12px;">Read &rarr;</a>' if a.get("url") else ""
                vt_html += _card(
                    f'{_esc(a.get("title", ""))}{link}',
                    body=_esc(a.get("summary", "")),
                    meta=_esc(vt.get("source_description", "")),
                    accent_left=_C["blue"],
                )
        body += _section("From Your Vault", vt_html)

    story_count = d.get("story_count", 0)
    topic_count = d.get("topic_count", 0)

    return _email_wrapper(
        "News Pulse",
        d.get("date", ""),
        f"{story_count} stories across {topic_count} topics, curated from your work context",
        body,
        hero_uri=hero,
    )


# ── Plan My Week ──────────────────────────────────────────────────────────────

def render_plan_my_week_email(json_data: dict[str, Any], images_dir: Path) -> str:
    d = json_data
    hero = _find_hero_image(images_dir)
    week = d.get("week", {})

    summary_html = ""
    if d.get("executive_summary"):
        summary_html = (
            f'<div style="background:#f0f4ff;border-left:4px solid {_C["accent"]};'
            f'border-radius:0 8px 8px 0;padding:16px 20px;margin-bottom:24px;'
            f'font-size:15px;color:{_C["body_text"]};line-height:1.6;">'
            f'{_esc(d["executive_summary"])}</div>'
        )

    days_html = ""
    days = d.get("days", [])
    if days:
        density_colors = {"light": _C["green"], "moderate": _C["yellow"], "heavy": _C["red"]}
        cells = ""
        for day in days:
            mc = day.get("meetings", {})
            dens = day.get("density", "moderate")
            dc = density_colors.get(dens, _C["muted"])
            cells += (
                f'<td style="text-align:center;padding:10px 4px;border:1px solid {_C["body_border"]};'
                f'border-radius:6px;vertical-align:top;width:{100 // max(len(days), 1)}%;">'
                f'<div style="font-weight:700;font-size:13px;color:{_C["body_text"]};">{_esc(day.get("day_name", "")[:3])}</div>'
                f'<div style="font-size:11px;color:{_C["body_muted"]};">{_esc(day.get("date", ""))}</div>'
                f'<div style="font-size:22px;font-weight:800;color:{dc};margin-top:4px;">{mc.get("count", 0)}</div>'
                f'<div style="font-size:10px;color:{_C["body_muted"]};">{mc.get("hours", 0)}h mtgs</div>'
                f'</td>'
            )
        days_html = (
            f'<table width="100%" cellpadding="0" cellspacing="4" style="margin-bottom:24px;">'
            f'<tr>{cells}</tr></table>'
        )

    pris_html = ""
    for p in d.get("priorities", []):
        pris_html += _card(
            f'{_status_pill(p.get("status", ""))} &nbsp; {_esc(p.get("name", ""))}',
            meta=f'Owner: {_esc(p.get("owner", "--"))} &middot; Deadline: {_esc(p.get("deadline", "--"))}',
        )

    deliverables_html = ""
    for dl in d.get("deliverables", []):
        deliverables_html += _card(
            _esc(dl.get("name", "")),
            meta=f'Owed to: {_esc(dl.get("owed_to", "--"))} &middot; Deadline: {_esc(dl.get("deadline", "--"))} &middot; Planned: {_esc(dl.get("planned_day", "--"))}',
            accent_left={"Overdue": _C["red"], "Due": _C["yellow"]}.get(dl.get("status", ""), _C["accent"]),
        )

    day_details_html = ""
    for day in days:
        mc = day.get("meetings", {})
        items = ""
        for name in mc.get("names", []):
            items += f'<li style="margin-bottom:4px;">{_esc(name)}</li>'
        for w in day.get("priority_work", []):
            items += f'<li style="margin-bottom:4px;"><b>Focus:</b> {_esc(w)}</li>'
        for fu in day.get("follow_ups", []):
            items += f'<li style="margin-bottom:4px;"><b>Follow-up:</b> {_esc(fu)}</li>'
        if items:
            day_details_html += _card(
                f'{_esc(day.get("day_name", ""))} {_esc(day.get("date", ""))} &mdash; {mc.get("count", 0)} meetings, {mc.get("hours", 0)}h',
                body=f'<ul style="margin:8px 0 0 16px;padding:0;font-size:13px;">{items}</ul>',
            )

    commits_html = ""
    for c in d.get("commitments_you_owe", []):
        commits_html += _card(_esc(c.get("commitment", "")), meta=f'To: {_esc(c.get("owed_to", ""))} &middot; Deadline: {_esc(c.get("deadline", ""))}', accent_left=_C["orange"])
    for c in d.get("commitments_owed_to_you", []):
        commits_html += _card(f'{_esc(c.get("person", ""))}: {_esc(c.get("commitment", ""))}', meta=f'Deadline: {_esc(c.get("deadline", ""))}')

    risks_html = ""
    for r in d.get("risks", []):
        risks_html += _card(_esc(r.get("title", "")), body=_esc(r.get("detail", "")), accent_left=_severity_color(r.get("severity", "medium")))

    body = summary_html + days_html + _analysis_card(d.get("analysis"))
    if pris_html:
        body += _section("Priorities", pris_html)
    if deliverables_html:
        body += _section("Deliverables", deliverables_html)
    if day_details_html:
        body += _section("Day-by-Day Plan", day_details_html)
    if commits_html:
        body += _section("Open Commitments", commits_html)
    if risks_html:
        body += _section("Risks & Watch Items", risks_html)

    return _email_wrapper(
        "Weekly Plan",
        f'{week.get("start", "")} to {week.get("end", "")}',
        f'{len(days)} days planned',
        body,
        hero_uri=hero,
    )


# ── Weekly Status ─────────────────────────────────────────────────────────────

def render_weekly_status_email(json_data: dict[str, Any], images_dir: Path) -> str:
    d = json_data
    hero = _find_hero_image(images_dir)
    m = d.get("metrics", {})
    cs = m.get("commitment_score", {})

    metrics = _metrics_bar([
        (str(m.get("meetings_total", 0)), "Meetings"),
        (str(m.get("emails_received", 0)), "Emails In"),
        (str(m.get("emails_sent", 0)), "Emails Out"),
        (str(m.get("accomplishments_count", 0)), "Wins"),
        (f'{cs.get("percent", 0)}%', "Commitment Score"),
    ])

    summary_html = ""
    if d.get("summary"):
        summary_html = (
            f'<div style="background:#f0f4ff;border-left:4px solid {_C["accent"]};'
            f'border-radius:0 8px 8px 0;padding:16px 20px;margin-bottom:24px;'
            f'font-size:15px;color:{_C["body_text"]};line-height:1.6;">'
            f'{_esc(d["summary"])}</div>'
        )

    accomplishments_html = ""
    for a in d.get("accomplishments", []):
        cat = a.get("category", "")
        cat_pill = _pill(cat, _C["accent"]) if cat else ""
        accomplishments_html += _card(
            f'{cat_pill} {_esc(a.get("title", ""))}' if cat_pill else _esc(a.get("title", "")),
            body=_esc(a.get("impact", "")),
            accent_left=_C["green"],
        )

    pva_html = ""
    for item in d.get("plan_vs_actual", []):
        pva_html += _card(
            f'{_status_pill(item.get("status", ""))} &nbsp; {_esc(item.get("item", ""))}',
            meta=f'Source: {_esc(item.get("source", ""))}',
        )

    blockers_html = ""
    for b in d.get("blockers", []):
        blockers_html += _card(
            _esc(b.get("title", "")),
            body=f'<b>Impact:</b> {_esc(b.get("impact", ""))}<br><b>Mitigation:</b> {_esc(b.get("mitigation", ""))}',
            accent_left=_severity_color(b.get("severity", "medium")),
        )

    value_html = ""
    for v in d.get("value_delivered", []):
        value_html += _card(_esc(v.get("statement", "")), body=_esc(v.get("detail", "")), accent_left=_C["green"])

    next_week_html = ""
    for n in d.get("next_week", []):
        next_week_html += _card(_esc(n.get("item", "")), meta=_esc(n.get("date", "")))

    body = metrics + _analysis_card(d.get("analysis")) + summary_html
    if accomplishments_html:
        body += _section("Key Accomplishments", accomplishments_html)
    if pva_html:
        body += _section("Plan vs. Actual", pva_html)
    if value_html:
        body += _section("Value Delivered", value_html)
    if blockers_html:
        body += _section("Blockers & Risks", blockers_html)
    if next_week_html:
        body += _section("Next Week Focus", next_week_html)

    dr = d.get("date_range", {})
    return _email_wrapper(
        "Weekly Status Report",
        f'{dr.get("start", "")} to {dr.get("end", "")}',
        f'{m.get("accomplishments_count", 0)} accomplishments &middot; {cs.get("percent", 0)}% commitment score',
        body,
        hero_uri=hero,
    )


# ── Commitment Tracker ────────────────────────────────────────────────────────

def render_commitment_tracker_email(json_data: dict[str, Any], images_dir: Path) -> str:
    d = json_data
    hero = _find_hero_image(images_dir)

    score_html = ""
    if d.get("health_score") is not None:
        score_html = (
            f'<table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:16px;"><tr>'
            + _score_badge(d.get("health_score", 0), "Health")
            + _metric_box(str(d.get("total_open", 0)), "Open")
            + _metric_box(str(d.get("total_overdue", 0)), "Overdue")
            + _metric_box(str(len(d.get("others_owe_you", []))), "Owed to You")
            + '</tr></table>'
        )

    metrics = _metrics_bar([
        (str(d.get("total_open", 0)), "Open"),
        (str(d.get("total_overdue", 0)), "Overdue"),
        (str(len(d.get("others_owe_you", []))), "Owed to You"),
        (str(len(d.get("recently_completed", []))), "Completed"),
    ]) if not score_html else score_html

    yours_html = ""
    for c in d.get("your_commitments", []):
        status = c.get("status", "open")
        status_label = c.get("status", "open")
        color = {"overdue": _C["red"], "open": _C["orange"], "completed": _C["green"],
                 "not_started": _C["muted"], "in_progress": _C["blue"],
                 "blocked": _C["red"], "unverified": _C["muted"]}.get(status, _C["muted"])
        meta_parts = []
        if c.get("priority"):
            meta_parts.append(f'<b>{c["priority"]}</b>')
        if c.get("effort"):
            meta_parts.append(f'[{c["effort"]}]')
        if c.get("owed_to"):
            meta_parts.append(f'To: {_esc(c["owed_to"])}')
        if c.get("deadline") and c["deadline"] != "—":
            meta_parts.append(f'Due: {_esc(c["deadline"])}')
        if c.get("project"):
            meta_parts.append(f'Project: {_esc(c["project"])}')
        progress = ""
        if c.get("percent_complete") is not None:
            progress = _progress_bar(c["percent_complete"])
        yours_html += _card(
            f'{_pill(status_label, color)} &nbsp; {_esc(c.get("commitment", ""))}',
            body=progress,
            meta=" &middot; ".join(meta_parts),
            accent_left=color,
        )

    others_html = ""
    for c in d.get("others_owe_you", []):
        status = c.get("status", "open")
        color = {"overdue": _C["red"], "open": _C["blue"]}.get(status, _C["muted"])
        others_html += _card(
            f'{_esc(c.get("person", ""))}: {_esc(c.get("commitment", ""))}',
            meta=f'Deadline: {_esc(c.get("deadline", "--"))} &middot; Source: {_esc(c.get("source", ""))}',
            accent_left=color,
        )

    overdue_html = ""
    for o in d.get("overdue_items", []):
        overdue_html += _card(
            _esc(o.get("commitment", "")),
            body=f'<b>Risk:</b> {_esc(o.get("risk", ""))}',
            meta=f'To: {_esc(o.get("owed_to", ""))} &middot; {o.get("days_overdue", 0)} days overdue',
            accent_left=_C["red"],
        )

    body = metrics + _analysis_card(d.get("analysis"))
    if overdue_html:
        body += _section("Overdue Items", overdue_html)
    if yours_html:
        body += _section("Your Open Commitments", yours_html)
    if others_html:
        body += _section("Others Owe You", others_html)

    completed = d.get("recently_completed", [])
    if completed:
        c_html = ""
        for c in completed:
            c_html += _card(_esc(c.get("commitment", "")), meta=f'Completed: {_esc(c.get("completed_date", ""))}', accent_left=_C["green"])
        body += _section("Recently Completed", c_html)

    return _email_wrapper(
        "Commitment Tracker",
        d.get("date", ""),
        f'{d.get("total_open", 0)} open &middot; {d.get("total_overdue", 0)} overdue',
        body,
        hero_uri=hero,
    )


# ── Project Brief ─────────────────────────────────────────────────────────────

def render_project_brief_email(json_data: dict[str, Any], images_dir: Path) -> str:
    d = json_data
    hero = _find_hero_image(images_dir)

    body = _analysis_card(d.get("analysis"))
    for proj in d.get("projects", []):
        status = proj.get("status", "")
        status_color = {"On Track": _C["green"], "At Risk": _C["yellow"], "Blocked": _C["red"]}.get(status, _C["muted"])

        proj_header = (
            f'<div style="margin-top:28px;margin-bottom:12px;">'
            f'<div style="display:flex;align-items:center;gap:12px;">'
            f'{_pill(status, status_color)}'
            f'<span style="font-size:18px;font-weight:700;color:{_C["body_text"]};">{_esc(proj.get("name", ""))}</span>'
            f'</div>'
            f'<div style="font-size:14px;color:{_C["body_text"]};margin-top:8px;line-height:1.6;">{_esc(proj.get("summary", ""))}</div>'
            f'</div>'
        )
        body += proj_header

        stakeholders = proj.get("stakeholders", [])
        if stakeholders:
            sh = ""
            for s in stakeholders:
                sh += _card(f'{_esc(s.get("name", ""))} &mdash; {_esc(s.get("role", ""))}', meta=_esc(s.get("last_activity", "")))
            body += _section(f'{_esc(proj.get("name", ""))} Stakeholders', sh)

        blockers = proj.get("blockers", [])
        if blockers:
            bh = ""
            for b in blockers:
                bh += _card(_esc(b.get("title", "")), body=_esc(b.get("impact", "")), accent_left=_severity_color(b.get("severity", "medium")))
            body += _section("Blockers & Risks", bh)

        decisions = proj.get("open_decisions", [])
        if decisions:
            dh = ""
            for d in decisions:
                if isinstance(d, str):
                    dh += _card(_esc(d), accent_left=_C["orange"])
                else:
                    detail_parts = []
                    if d.get("waiting_on"):
                        detail_parts.append(f'<b>Waiting on:</b> {_esc(d["waiting_on"])}')
                    if d.get("recommended_action"):
                        detail_parts.append(f'<b>Action:</b> {_esc(d["recommended_action"])}')
                    if d.get("deadline"):
                        detail_parts.append(f'<b>Deadline:</b> {_esc(d["deadline"])}')
                    meta = "<br>".join(detail_parts)
                    dh += _card(_esc(d.get("decision", "")), meta=meta, accent_left=_C["orange"])
            body += _section("Decisions Needed", dh)

        steps = proj.get("next_steps", [])
        if steps:
            items = "".join(f'<li style="margin-bottom:6px;">{_esc(s)}</li>' for s in steps)
            body += _section("Next Steps", f'<ul style="margin:0 0 0 16px;padding:0;font-size:14px;">{items}</ul>')

        comms = proj.get("recent_communications", [])
        if comms:
            ch = ""
            for c in comms:
                ch += _card(_esc(c.get("subject", "")), body=_esc(c.get("summary", "")), meta=f'From: {_esc(c.get("from", ""))} &middot; {_esc(c.get("date", ""))}')
            body += _section("Recent Communications", ch)

    return _email_wrapper(
        "Project Brief",
        d.get("date", ""),
        f'{len(d.get("projects", []))} projects tracked',
        body,
        hero_uri=hero,
    )


# ── Focus Audit ───────────────────────────────────────────────────────────────

def render_focus_audit_email(json_data: dict[str, Any], images_dir: Path) -> str:
    d = json_data
    hero = _find_hero_image(images_dir)
    m = d.get("metrics", {})

    metrics = _metrics_bar([
        (f'{m.get("deep_work_hours", 0):.1f}h', "Deep Work"),
        (f'{m.get("meeting_hours", 0):.1f}h', "Meetings"),
        (str(m.get("context_switches", 0)), "Switches"),
        (f'{m.get("longest_focus_block_minutes", 0)}m', "Best Focus"),
        (f'{m.get("meeting_load_percent", 0):.0f}%', "Meeting Load"),
    ])

    summary_html = ""
    if d.get("summary"):
        summary_html = (
            f'<div style="background:#f0f4ff;border-left:4px solid {_C["accent"]};'
            f'border-radius:0 8px 8px 0;padding:16px 20px;margin-bottom:24px;'
            f'font-size:15px;color:{_C["body_text"]};line-height:1.6;">'
            f'{_esc(d["summary"])}</div>'
        )

    focus_html = ""
    for fw in d.get("focus_windows", []):
        focus_html += _card(
            f'{_esc(fw.get("start", ""))} &mdash; {fw.get("duration_minutes", 0)} min',
            body=_esc(fw.get("context", "")),
            meta=_esc(fw.get("app", "")),
            accent_left=_C["green"],
        )

    apps_html = ""
    for app in d.get("top_apps", []):
        apps_html += _card(
            _esc(app.get("name", "")),
            meta=f'{app.get("hours", 0):.1f}h &middot; {_esc(app.get("category", ""))}',
        )

    frag_html = ""
    for f in d.get("fragmentation_hotspots", []):
        frag_html += _card(
            f'{_esc(f.get("hour", ""))} &mdash; {f.get("switches", 0)} switches',
            body=_esc(f.get("detail", "")),
            accent_left=_C["red"],
        )

    insights = d.get("insights", []) + d.get("recommendations", [])
    insights_html = ""
    if insights:
        items = "".join(f'<li style="margin-bottom:8px;">{_esc(i)}</li>' for i in insights)
        insights_html = f'<ul style="margin:0 0 0 16px;padding:0;font-size:14px;line-height:1.6;">{items}</ul>'

    body = metrics + _analysis_card(d.get("analysis")) + summary_html

    fv = d.get("focus_villain")
    if fv:
        villain_name = fv if isinstance(fv, str) else _esc(fv.get("name", ""))
        villain_detail = "" if isinstance(fv, str) else _esc(fv.get("detail", ""))
        body += _card(
            f"Focus Villain: {villain_name}",
            body=villain_detail,
            accent_left=_C["red"],
        )

    if focus_html:
        body += _section("Best Focus Windows", focus_html)
    if apps_html:
        body += _section("Top Apps", apps_html)
    if frag_html:
        body += _section("Fragmentation Hotspots", frag_html)
    if insights_html:
        body += _section("Insights & Recommendations", insights_html)

    return _email_wrapper(
        "Focus Audit",
        d.get("date", ""),
        f'{m.get("deep_work_hours", 0):.1f}h deep work &middot; {m.get("meeting_hours", 0):.1f}h meetings &middot; {m.get("context_switches", 0)} switches',
        body,
        hero_uri=hero,
    )


# ── Relationship CRM ─────────────────────────────────────────────────────────

def render_relationship_crm_email(json_data: dict[str, Any], images_dir: Path) -> str:
    d = json_data
    hero = _find_hero_image(images_dir)
    ns = d.get("network_summary", {})

    metrics = _metrics_bar([
        (str(d.get("active_contacts_count", 0)), "Active"),
        (str(ns.get("inner_circle_count", 0)), "Inner Circle"),
        (str(ns.get("growing_relationships", 0)), "Growing"),
        (str(ns.get("fading_relationships", 0)), "Fading"),
    ])

    top_html = ""
    for c in d.get("top_contacts", []):
        strength = c.get("strength", 0)
        bar = f'{"&#9733;" * strength}{"&#9734;" * (5 - strength)}'
        trend_color = {"growing": _C["green"], "stable": _C["blue"], "fading": _C["red"]}.get(c.get("trend", ""), _C["muted"])
        topics = ", ".join(c.get("primary_topics", [])[:3])
        channels = ", ".join(c.get("channels", []))
        top_html += _card(
            f'{_esc(c.get("name", ""))} <span style="color:{_C["body_muted"]};font-weight:400;font-size:12px;">{_esc(c.get("organization", ""))}</span>',
            body=f'<span style="color:{_C["accent"]};">{bar}</span> &nbsp; {_pill(c.get("trend", ""), trend_color)}<br>'
                 f'<span style="font-size:12px;color:{_C["body_muted"]};">Topics: {_esc(topics)} &middot; Channels: {_esc(channels)}</span>',
            meta=f'{c.get("interactions_7d", 0)} this week &middot; {c.get("interactions_30d", 0)} this month &middot; Last: {_esc(c.get("last_interaction", ""))}',
        )

    dormant_html = ""
    for dr in d.get("dormant_relationships", []):
        dormant_html += _card(
            _esc(dr.get("name", "")),
            body=f'Last contact: {_esc(dr.get("last_contact", ""))} &middot; Was active on: {_esc(dr.get("was_active", ""))}',
            meta=f'Suggested: {_esc(dr.get("suggested_action", ""))}',
            accent_left=_C["yellow"],
        )

    new_html = ""
    for n in d.get("new_contacts", []):
        new_html += _card(_esc(n.get("name", "")), body=_esc(n.get("context", "")), meta=_esc(n.get("channel", "")), accent_left=_C["green"])

    body = metrics + _analysis_card(d.get("analysis"))
    if top_html:
        body += _section("Top Contacts", top_html)
    if dormant_html:
        body += _section("Reconnect", dormant_html)
    if new_html:
        body += _section("New Contacts", new_html)

    reconnect = ns.get("suggested_reconnections", [])
    if reconnect:
        items = "".join(f'<li style="margin-bottom:4px;">{_esc(r)}</li>' for r in reconnect)
        body += _section("Suggested Reconnections", f'<ul style="margin:0 0 0 16px;padding:0;font-size:14px;">{items}</ul>')

    return _email_wrapper(
        "Relationship CRM",
        d.get("date", ""),
        f'{d.get("active_contacts_count", 0)} active contacts &middot; {d.get("period_days", 7)}-day view',
        body,
        hero_uri=hero,
    )


# ── Team Manager ──────────────────────────────────────────────────────────────

def render_team_manager_email(json_data: dict[str, Any], images_dir: Path) -> str:
    d = json_data
    hero = _find_hero_image(images_dir)
    oi = d.get("open_items_summary", {})

    metrics = _metrics_bar([
        (str(d.get("team_size", 0)), "Team Size"),
        (str(oi.get("yours", 0)), "Your Items"),
        (str(oi.get("theirs", 0)), "Their Items"),
        (str(len(d.get("attention_needed", []))), "Needs Attention"),
    ])

    attention_html = ""
    for a in d.get("attention_needed", []):
        attention_html += _card(
            _esc(a.get("name", "")),
            body=_esc(a.get("reason", "")),
            meta=f'Action: {_esc(a.get("suggested_action", ""))}',
            accent_left=_C["red"],
        )

    members_html = ""
    for m in d.get("team_members", []):
        status = m.get("status", "green")
        sc = {"green": _C["green"], "yellow": _C["yellow"], "red": _C["red"]}.get(status, _C["muted"])
        focus = ", ".join(m.get("current_focus", [])[:3])
        wins = ", ".join(m.get("recent_wins", [])[:2])
        topics = "; ".join(m.get("suggested_1_1_topics", [])[:3])
        members_html += _card(
            f'{_pill(status, sc)} &nbsp; {_esc(m.get("name", ""))} <span style="color:{_C["body_muted"]};font-weight:400;font-size:12px;">{_esc(m.get("role", ""))}</span>',
            body=f'<b>Focus:</b> {_esc(focus)}' + (f'<br><b>Wins:</b> {_esc(wins)}' if wins else '') + (f'<br><b>1:1 topics:</b> {_esc(topics)}' if topics else ''),
            meta=f'Last 1:1: {_esc(m.get("last_one_on_one", "--"))} &middot; {m.get("interactions_7d", 0)} interactions this week',
        )

    wins_html = ""
    wins = d.get("team_wins", [])
    if wins:
        items = "".join(f'<li style="margin-bottom:6px;">{_esc(w)}</li>' for w in wins)
        wins_html = f'<ul style="margin:0 0 0 16px;padding:0;font-size:14px;">{items}</ul>'

    body = metrics + _analysis_card(d.get("analysis"))
    if attention_html:
        body += _section("Needs Attention", attention_html)
    if members_html:
        body += _section("Team Members", members_html)
    if wins_html:
        body += _section("Team Wins", wins_html)

    return _email_wrapper(
        "Team Manager",
        d.get("date", ""),
        f'{d.get("team_size", 0)} team members',
        body,
        hero_uri=hero,
    )


# ── Dispatcher ────────────────────────────────────────────────────────────────

_RENDERERS: dict[str, Any] = {
    "morning-brief": render_morning_brief_email,
    "news-pulse": render_news_pulse_email,
    "plan-my-week": render_plan_my_week_email,
    "weekly-status": render_weekly_status_email,
    "commitment-tracker": render_commitment_tracker_email,
    "project-brief": render_project_brief_email,
    "focus-audit": render_focus_audit_email,
    "relationship-crm": render_relationship_crm_email,
    "team-manager": render_team_manager_email,
}


def render_rich_email(
    skill_name: str,
    json_data: dict[str, Any],
    images_dir: Path | str,
) -> str | None:
    """Render a rich HTML email for the given skill, or None if no renderer exists."""
    renderer = _RENDERERS.get(skill_name)
    if not renderer:
        return None
    try:
        return renderer(json_data, Path(images_dir))
    except Exception as exc:
        logger.error("Rich email render failed for %s: %s", skill_name, exc)
        return None
